### ISSUE TITLE
Some images don't load when extension is enabled

### ISSUE THREAD

**Issue by ezramorris** [kofifus/WhiteBuster#1]
I have observed that certain images on some websites don't load when WhiteBuster is enabled.

To reproduce:

1. Disable WhiteBuster from the Chrome extensions settings.
2. Go to [https://www.sheffield.gov.uk/](url).
3. Observe the Sheffield City Council logo is present at the top centre.
4. Enable WhiteBuster and select a background colour.
5. Reload the page. Observe the logo has disappeared.
6. From the WhiteBuster icon, select Disabled. Reload the page and observe the logo is still not present.

I have also observed this on many other websites, for instance a lot of the icons on Facebook are not present, and the image of Martin at the top left of [http://www.moneysavingexpert.com/](url) is missing.

**Comment by ezramorris** [comment]
I should add: I am using version 1.3.7, released a few days ago. I don't recall seeing this before, so maybe it is related to the new version.

**Comment by kofifus** [comment]
Yes this was a bug in 1.3.7 - thanks for reporting !

I uploaded 1.3.8 that should solve it. Please let me know.
