### ISSUE TITLE
No installer?

### ISSUE THREAD

**Issue by ghost** [kofifus/WhiteBuster#2]
I'm using https://github.com/Eloston/ungoogled-chromium so when I go to this page: 
  https://chrome.google.com/webstore/detail/whitebuster/kkgacobcjapebahjhkabbkacbpmddeco

there is no option to install the extension, and I see no INSTALL file in the repo.  I'm new to chromium, so this could be a PEBKAC issue.

**Comment by ghost** [comment]
Sorry, I think this is a PEBKAC now that I found this:

https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore

**Comment by kofifus** [comment]
The extention is here https://chrome.google.com/webstore/detail/whitebuster/kkgacobcjapebahjhkabbkacbpmddeco
